name: GitHub view gh obj

on:
  issue_comment:
    types: [created, deleted]
  issues:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

jobs:
  process_event:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Perform actions based on event
      run: |
        echo "Event type: ${{ github.event_name }}"
        echo "Action: ${{ github.event.action }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dump GitHub context
      id: github_context_step
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}
