name: Exemplo de GitHub ISSUE

on:
    issues:
      types: [opened]

jobs:
  list-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
            npm install 
            npm install @actions/github

      - name: Executar o script JavaScript
        run: node teste-issue.js
      
