name: Exemplo de GitHub Action

on:
  pull_request:
    types:
      - opened
      - closed
  issues:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  list-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
            npm install 
            npm install @actions/github

      - name: Executar o script JavaScript
        run: node script.js
      
      - name: Mostrar o valor do commit
        run: echo "O valor do commit é ${{ github.sha }}"

      - name: Verificar se o pull request foi mesclado
        if: github.event.pull_request.merged == true
        run: echo "O pull request foi mesclado!"

      - name: Criar enviroment github
        env:
          GITHUB_OBJECT: ${{ toJson(github) }}
        run: echo "O valor da env github é ${{ env.GITHUB_OBJECT }}"
      
      - name: Listar variáveis de ambiente
        run: |
          for var in $(compgen -e); do
            echo "$var=${!var}"
          done
