name: Exemplo de GitHub Action

on:
  pull_request:
    types:
      - opened
      - edited
  issues:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  list-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Listar variáveis de ambiente
        run: |
          for var in $(compgen -e); do
            echo "$var=${!var}"
          done
